### ISSUE TITLE
Question: How to join table using this libraries

### ISSUE THREAD

**Issue by cikaldev** [sluvanda/codeigniter4-datatables#1]
Hi @sluvanda , thanks for this small and great libraries.
i have one question, maybe you have / will give me a little sample. About how to join table using your libraries.

Best Regard's
ian

**Comment by sluvanda** [comment]
No table join feature as of this release. It only works with single table.

**Workaround**

- Create view in your db
- Create a model in CI4 for the view, just the same way you do for the table
- Use the model to query underlying view
